// Generated by gencpp from file py_perception/FilterCloudRequest.msg
// DO NOT EDIT!


#ifndef PY_PERCEPTION_MESSAGE_FILTERCLOUDREQUEST_H
#define PY_PERCEPTION_MESSAGE_FILTERCLOUDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sensor_msgs/PointCloud2.h>

namespace py_perception
{
template <class ContainerAllocator>
struct FilterCloudRequest_
{
  typedef FilterCloudRequest_<ContainerAllocator> Type;

  FilterCloudRequest_()
    : input_cloud()
    , topic()
    , pcdfilename()
    , operation(0)  {
    }
  FilterCloudRequest_(const ContainerAllocator& _alloc)
    : input_cloud(_alloc)
    , topic(_alloc)
    , pcdfilename(_alloc)
    , operation(0)  {
  (void)_alloc;
    }



   typedef  ::sensor_msgs::PointCloud2_<ContainerAllocator>  _input_cloud_type;
  _input_cloud_type input_cloud;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _topic_type;
  _topic_type topic;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pcdfilename_type;
  _pcdfilename_type pcdfilename;

   typedef int8_t _operation_type;
  _operation_type operation;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(VOXELGRID)
  #undef VOXELGRID
#endif
#if defined(_WIN32) && defined(PASSTHROUGH)
  #undef PASSTHROUGH
#endif
#if defined(_WIN32) && defined(PLANESEGMENTATION)
  #undef PLANESEGMENTATION
#endif
#if defined(_WIN32) && defined(CLUSTEREXTRACTION)
  #undef CLUSTEREXTRACTION
#endif

  enum {
    VOXELGRID = 0,
    PASSTHROUGH = 1,
    PLANESEGMENTATION = 2,
    CLUSTEREXTRACTION = 3,
  };


  typedef boost::shared_ptr< ::py_perception::FilterCloudRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::py_perception::FilterCloudRequest_<ContainerAllocator> const> ConstPtr;

}; // struct FilterCloudRequest_

typedef ::py_perception::FilterCloudRequest_<std::allocator<void> > FilterCloudRequest;

typedef boost::shared_ptr< ::py_perception::FilterCloudRequest > FilterCloudRequestPtr;
typedef boost::shared_ptr< ::py_perception::FilterCloudRequest const> FilterCloudRequestConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::py_perception::FilterCloudRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::py_perception::FilterCloudRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::py_perception::FilterCloudRequest_<ContainerAllocator1> & lhs, const ::py_perception::FilterCloudRequest_<ContainerAllocator2> & rhs)
{
  return lhs.input_cloud == rhs.input_cloud &&
    lhs.topic == rhs.topic &&
    lhs.pcdfilename == rhs.pcdfilename &&
    lhs.operation == rhs.operation;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::py_perception::FilterCloudRequest_<ContainerAllocator1> & lhs, const ::py_perception::FilterCloudRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace py_perception

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::py_perception::FilterCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::py_perception::FilterCloudRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::py_perception::FilterCloudRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad4d28c90b14c44e0a78e17b92ebb1e8";
  }

  static const char* value(const ::py_perception::FilterCloudRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad4d28c90b14c44eULL;
  static const uint64_t static_value2 = 0x0a78e17b92ebb1e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "py_perception/FilterCloudRequest";
  }

  static const char* value(const ::py_perception::FilterCloudRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request\n"
"sensor_msgs/PointCloud2 input_cloud\n"
"string topic\n"
"#if empty, use data present in input_cloud\n"
"string pcdfilename\n"
"\n"
"# Removes objects outside a defined grid pattern x,y,z\n"
"byte VOXELGRID=0\n"
"\n"
"# Removes the objects based on volume of space\n"
"byte PASSTHROUGH=1\n"
"\n"
"# Issolate objects located along the largest flat surface (floor)\n"
"byte PLANESEGMENTATION=2\n"
"\n"
"# Determine clusters based on pcd density to identify multiple objects\n"
"byte CLUSTEREXTRACTION=3\n"
"\n"
"# Operation to be performed\n"
"byte operation\n"
"\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointCloud2\n"
"# This message holds a collection of N-dimensional points, which may\n"
"# contain additional information such as normals, intensity, etc. The\n"
"# point data is stored as a binary blob, its layout described by the\n"
"# contents of the \"fields\" array.\n"
"\n"
"# The point cloud data may be organized 2d (image-like) or 1d\n"
"# (unordered). Point clouds organized as 2d images may be produced by\n"
"# camera depth sensors such as stereo or time-of-flight.\n"
"\n"
"# Time of sensor data acquisition, and the coordinate frame ID (for 3d\n"
"# points).\n"
"Header header\n"
"\n"
"# 2D structure of the point cloud. If the cloud is unordered, height is\n"
"# 1 and width is the length of the point cloud.\n"
"uint32 height\n"
"uint32 width\n"
"\n"
"# Describes the channels and their layout in the binary data blob.\n"
"PointField[] fields\n"
"\n"
"bool    is_bigendian # Is this data bigendian?\n"
"uint32  point_step   # Length of a point in bytes\n"
"uint32  row_step     # Length of a row in bytes\n"
"uint8[] data         # Actual point data, size is (row_step*height)\n"
"\n"
"bool is_dense        # True if there are no invalid points\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: sensor_msgs/PointField\n"
"# This message holds the description of one point entry in the\n"
"# PointCloud2 message format.\n"
"uint8 INT8    = 1\n"
"uint8 UINT8   = 2\n"
"uint8 INT16   = 3\n"
"uint8 UINT16  = 4\n"
"uint8 INT32   = 5\n"
"uint8 UINT32  = 6\n"
"uint8 FLOAT32 = 7\n"
"uint8 FLOAT64 = 8\n"
"\n"
"string name      # Name of field\n"
"uint32 offset    # Offset from start of point struct\n"
"uint8  datatype  # Datatype enumeration, see above\n"
"uint32 count     # How many elements in the field\n"
;
  }

  static const char* value(const ::py_perception::FilterCloudRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.input_cloud);
      stream.next(m.topic);
      stream.next(m.pcdfilename);
      stream.next(m.operation);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FilterCloudRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::py_perception::FilterCloudRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::py_perception::FilterCloudRequest_<ContainerAllocator>& v)
  {
    s << indent << "input_cloud: ";
    s << std::endl;
    Printer< ::sensor_msgs::PointCloud2_<ContainerAllocator> >::stream(s, indent + "  ", v.input_cloud);
    s << indent << "topic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.topic);
    s << indent << "pcdfilename: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pcdfilename);
    s << indent << "operation: ";
    Printer<int8_t>::stream(s, indent + "  ", v.operation);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PY_PERCEPTION_MESSAGE_FILTERCLOUDREQUEST_H
